services:
  drupal:
    image: drupal:latest
    volumes:
      - ./drupal-data:/opt/drupal/
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    volumes:
      - ./mariadb-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal

  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080